# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-25 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('a', 'Abierto'), ('p', 'Pendiente'), ('ep', 'En Proceso'), ('r', 'Resuelto'), ('c', 'Cerrado')], max_length=2)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
